import os

DEFAULT_MODEL = "gpt-3.5-turbo"


def get_config_dir():
    xdg = os.environ.get("XDG_CONFIG_HOME")
    if xdg:
        return os.path.join(xdg, "cmdmaster-pro")
    return os.path.expanduser("~/.config/cmdmaster-pro")


def get_config_file():
    return os.path.join(get_config_dir(), "ai_config.py")


def _load_config_from_file(path):
    """Load AI_URL, AI_TOKEN, AI_MODEL from a Python config file."""
    config = {}
    try:
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line.startswith("#") or "=" not in line:
                    continue
                key, _, value = line.partition("=")
                key = key.strip()
                value = value.strip().strip('"').strip("'")
                if key in ("AI_URL", "AI_TOKEN", "AI_MODEL"):
                    config[key] = value
    except OSError:
        pass
    return config


def load_ai_config():
    """Load AI config with priority: env vars > user config file."""
    url = os.environ.get("CMDMASTER_AI_URL")
    token = os.environ.get("CMDMASTER_AI_TOKEN")
    model = os.environ.get("CMDMASTER_AI_MODEL")

    config_file = get_config_file()
    if os.path.exists(config_file):
        file_config = _load_config_from_file(config_file)
        url = url or file_config.get("AI_URL")
        token = token or file_config.get("AI_TOKEN")
        model = model or file_config.get("AI_MODEL")

    model = model or DEFAULT_MODEL
    return url, token, model


def is_ai_configured(url, token):
    return bool(url and token)


def set_ai_config(config_type, value):
    """Write AI config to the user config directory."""
    config_dir = get_config_dir()
    os.makedirs(config_dir, exist_ok=True)
    config_file = get_config_file()

    if os.path.exists(config_file):
        with open(config_file, "r", encoding="utf-8") as f:
            lines = f.readlines()
    else:
        lines = [
            "# AI Configuration\n",
            "# Generated by cmdmaster-pro\n\n",
            f'AI_URL = ""\n',
            f'AI_TOKEN = ""\n',
            f'AI_MODEL = "{DEFAULT_MODEL}"\n',
        ]

    key_map = {"url": "AI_URL", "token": "AI_TOKEN", "model": "AI_MODEL"}
    target_key = key_map.get(config_type)
    if not target_key:
        return config_file

    updated = False
    for i, line in enumerate(lines):
        if line.strip().startswith(f"{target_key} = "):
            lines[i] = f'{target_key} = "{value}"\n'
            updated = True
            break
    if not updated:
        lines.append(f'{target_key} = "{value}"\n')

    with open(config_file, "w", encoding="utf-8") as f:
        f.writelines(lines)

    return config_file


def reload_module_config():
    """Reload config into the api module after changes."""
    from cmdmaster import api as api_module

    url, token, model = load_ai_config()
    api_module.AI_URL = url
    api_module.AI_TOKEN = token
    api_module.AI_MODEL = model
